-- CREATE TABLE customers (
--     id INT(10) AUTO_INCREMENT PRIMARY KEY,
--     first_name VARCHAR(256) NOT NULL,
--     last_name VARCHAR(256) NOT NULL,
--     gender CHAR(1) NOT NULL,
--     email VARCHAR(256) NOT NULL UNIQUE,
--     password VARCHAR(256) NOT NULL
-- );